name: demo_responsive
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sliding_up_panel: ^2.0.0+1
  flutter_password_strength: ^0.1.6
  carousel_slider: ^4.1.1
  flutter_spinkit: ^5.1.0
  getwidget: ^2.0.4
  sizer: ^2.0.15
  http: ^0.13.4
  connectivity_plus: ^2.3.0
  google_fonts: ^2.1.0
  get_storage: ^2.0.3
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.2.0
  intl: ^0.17.0
  cached_network_image: ^3.2.0
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  # flutter_map_arcgis:
  flutter_map_arcgis: ^2.0.4
  flutter_map:
  latlong2:
  # dio: ^4.0.6

  geocoding: ^2.0.5
  flutter_polyline_points: ^1.0.0
  # geocoder: ^0.2.1

  # Local
  custom_popup_menu:
    path: ./package/custom_popup_menu

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
